is_debug: true
dir:
    log: /data/logs/xc-data-processor
    data: /data/xc-data-processor
    cache: ./cache
    template: ./templates
db:
    host: localhost
    port: 3306
    user: xc_data_processor
    password: xc-data-processor
    dbname: xc_data_processor
memcached:
    host: localhost
    port: 11211
aws:
    profile: xc-data-processor
    region: cn-north-1
dynamodb:
    prefix: xc-data-processor-
